# Site settings
site: KAl Blogs
title: KALs blog
keywords: ephesus, blog
description: >-
  welcome to my cave away from what you guys know as civilization "Social media"
lang: en-US
timezone:  Africa/cairo
repo: https://github.com/KALs3/KALs3.github.io # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Khaled
  bio: Software developer, AI prompter, and a bad writer who also loves music and photography.
  picture: assets/images/me.jpg 
  github: KALs # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  instagram: instagram_username # instagram username
  youtube: https://www.youtube.com/channel/youtube_username # youtube username
  linkedin: linkedin_username # linkedin username
  email: your-email@email.com # email adress


# URL settings
url: "http://127.0.0.1:4000" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
